version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:12

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Authenticate with Registry
          command: |
            echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" > ~/.npmrc
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          paths:
            - ~/.cache
          key: v2-dependencies-{{ checksum "package.json" }}
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths: .
  cypress:
    <<: *defaults
    steps:
      - attach_workspace: # We need the code available to be able to run the tests.
          at: ~/repo
      - restore_cache: # We need to restore the cache to get the Cypress binary.
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-
      - run:
          name: Cypress
          command: yarn cypress
  lighthouse:
    <<: *defaults
    docker:
      - image: circleci/node:10.16-browsers
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Install Lighthouse
          command: yarn global add @lhci/cli@0.3.x
      - run:
          name: Lighthouse CI Autorun
          command: lhci autorun || echo "LHCI failed!"
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Deploy
          command: yarn gh-pages

workflows:
  version: 2
  website:
    jobs:
      - build:
          context: open-source
      - cypress:
          requires:
            - build
      - lighthouse:
          context: personal-aws
          requires:
            - build
      - deploy:
          context: personal-aws
          requires:
            - cypress
            - lighthouse
          filters:
            branches:
              only: /^master$/
