version: 2.1

defaults: &defaults
  working_directory: /mnt/ramdisk/repo
  docker:
    - image: sammarks/circleci-puppeteer:latest

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Authenticate with Registry
          command: |
            echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" > ~/.npmrc
      - restore_cache:
          keys:
            - v4-dependencies-{{ checksum "yarn.lock" }}
            - v4-dependencies-
      - run:
          name: Install Dependencies
          command: yarn --frozen-lockfile --cache-folder /mnt/ramdisk/yarn
      - save_cache:
          paths:
            - /mnt/ramdisk/yarn
            - /mnt/ramdisk/repo/node_modules
          key: v4-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Lint
          command: yarn lint
      - persist_to_workspace:
          root: /mnt/ramdisk/repo
          paths: .
  cypress:
    <<: *defaults
    docker:
      - image: cypress/base:12.16.1
        environment:
          TERM: xterm
    steps:
      - attach_workspace: # We need the code available to be able to run the tests.
          at: /mnt/ramdisk/repo
      - run:
          name: Cypress Install
          command: ./node_modules/.bin/cypress install
      - run:
          name: Cypress
          command: yarn cypress
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /mnt/ramdisk/repo
      - run:
          name: Clean
          command: ./node_modules/.bin/gatsby clean
      - run:
          name: Build
          command: yarn build
      - run:
          name: Copy CNAME & remove meta folder
          command: |
            cp CNAME ./public/
            rm -rf ./public/__meta
      - persist_to_workspace:
          root: /mnt/ramdisk/repo
          paths: ./public
  lighthouse:
    <<: *defaults
    docker:
      - image: circleci/node:10.16-browsers
    steps:
      - attach_workspace:
          at: /mnt/ramdisk/repo
      - run:
          name: Lighthouse
          command: yarn lighthouse
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /mnt/ramdisk/repo
      - run:
          name: Set Git Identification
          command: |
            git config --global user.email "sam+ci@sammarks.me"
            git config --global user.name "CI Deploy"
      - run:
          name: Deploy
          command: yarn deploy

workflows:
  version: 2
  website:
    jobs:
      - test:
          context: open-source
          filters:
            branches:
              ignore: /^gh-pages$/
      - cypress:
          requires:
            - test
          filters:
            branches:
              ignore: /^gh-pages$/
      - build:
          context: open-source
          requires:
            - test
          filters:
            branches:
              ignore: /^gh-pages$/
      - lighthouse:
          context: personal-aws
          requires:
            - build
          filters:
            branches:
              ignore: /^gh-pages$/
      - deploy:
          context: personal-aws
          requires:
            - cypress
            - lighthouse
          filters:
            branches:
              only: /^master$/
