version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:12

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Authenticate with Registry
          command: |
            echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" > ~/.npmrc
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          paths:
            - ~/.cache
          key: v2-dependencies-{{ checksum "package.json" }}
      - run:
          name: Lint
          command: yarn lint
      - persist_to_workspace:
          root: ~/repo
          paths: .
  cypress:
    <<: *defaults
    docker:
      - image: cypress/base:8
        environment:
          TERM: xterm
    steps:
      - attach_workspace: # We need the code available to be able to run the tests.
          at: ~/repo
      - run:
          name: Cypress Install
          command: ./node_modules/.bin/cypress install
      - run: # We need to rebuild deps because we're on a different node version.
          name: Rebuild
          command: npm rebuild
      - run:
          name: Cypress
          command: yarn cypress
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths: ./public
  lighthouse:
    <<: *defaults
    docker:
      - image: circleci/node:10.16-browsers
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Lighthouse
          command: yarn lighthouse
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Deploy
          command: yarn deploy

workflows:
  version: 2
  website:
    jobs:
      - test:
          context: open-source
          filters:
            branches:
              ignore: /^gh-pages$/
      - cypress:
          requires:
            - test
          filters:
            branches:
              ignore: /^gh-pages$/
      - build:
          context: open-source
          requires:
            - test
          filters:
            branches:
              ignore: /^gh-pages$/
      - lighthouse:
          context: personal-aws
          requires:
            - build
          filters:
            branches:
              ignore: /^gh-pages$/
      - deploy:
          context: personal-aws
          requires:
            - cypress
            - lighthouse
          filters:
            branches:
              only: /^master$/
